osx_image: xcode10.1
language: objective-c
env:
  global:
  - FRAMEWORK_NAME=WindowTransitions
cache:
  directories:
  - Carthage
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
before_deploy:
- carthage archive $FRAMEWORK_NAME
after_deploy:
- pod trunk push
script:
- carthage build --no-skip-current --platform iOS --cache-builds
- pod lib lint
